### ISSUE TITLE
bug: InventoryClickEvent

### ISSUE THREAD

**Issue by madtomic** [amethyst-studio/ChestBlocker#2]
https://pastebin.com/ZJeXudsJ

When clicking outside the chest inventory. This error is send on console.

![image](https://user-images.githubusercontent.com/6004542/62424535-c1db3480-b69d-11e9-829f-e84da844137b.png)

**Comment by xCykrix** [comment]
Will fix later today.

**Comment by xCykrix** [comment]
Issues resolved in 81bc61c
