### ISSUE TITLE
bug: not blocking material

### ISSUE THREAD

**Issue by madtomic** [amethyst-studio/ChestBlocker#4]
****I have this bug as COOKED_BEEF suppose to be blocked and it's not**

EDIT: I just tested with other items and it is not blocking any of them as well.

![image](https://user-images.githubusercontent.com/6004542/62424488-f7335280-b69c-11e9-94e0-2e7a0c2ab6b4.png)

**Comment by madtomic** [comment]
I just tested with other items and it is not blocking any of them as well.

**Comment by xCykrix** [comment]
Any errors, and are you /op?

**Comment by madtomic** [comment]
I am not OP. Just a normal players. I am aware of the permissions.

**Comment by xCykrix** [comment]
I will investigate to see if I can replicate on 1.12.2 Paper Spigot once updates to main parser are finished.

**Comment by xCykrix** [comment]
Please reverify this issue still exists in latest release.  
https://github.com/amethyst-studio/ChestBlocker/releases

/cc @madtomic

**Comment by madtomic** [comment]
Using 1.0.2

    blocked-materials:
      - "WOOL"

I tried with that and the material isn't blocked and COOKED_BEEF is still not blacklisted

**Comment by madtomic** [comment]
This is what I find out. This seems to work with blacklist.

`  no-fish-allowed:
    blocked-names: []
    blocked-materials:
      - "COOKED_BEEF"
    blocked-containers:
      - "CHEST"
    use-names: false
    block-message: "&cYou may not store {item} into this {container}."`

**Comment by xCykrix** [comment]
Could you codeblock a full bugged config and a screenshot of item(s) that are not being blocked?

**Comment by xCykrix** [comment]
Use-names requires that you have a item with a custom name and that name is on a material.

**Comment by madtomic** [comment]
> Use-names requires that you have a item with a custom name and that name is on a material.

That explains the behavior. Then this is intended.

**Comment by xCykrix** [comment]
Yeah, bukkit doesn't actually give default items a name, as they are  handled by client locale.
